[general]
# On Windows, to start in the Windows-specific user directory:
# working_directory = "C:\\Users\\sergii"

[terminal]
shell = "nu"
# WARNING: On Windows with Chocolatey, use the absolute path of the actual nu.exe
# to avoid issues with Ctrl+C closing terminal window:
# shell = "C:\\Program Files\\nu\\bin\\nu.exe"
# args = []
# To automatically launch WSL (Linux container in Windows) in contained home directory
# program = "C:\\Windows\\System32\\wsl.exe"
# args = ["--cd", "~"]

[selection]
# This string contains all characters that are used as separators for "semantic words".
# Specifically exclude the colon character `:` to allow simple double-clicking
# to copy file paths with line and column numbers that Vim/Neovim understand.
semantic_escape_chars = ",â”‚`|\"' ()[]{}<>\t"

# Automatically copy to clipboard on selection
save_to_clipboard = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x001010"
foreground = "0xd0d0d0"

[colors.normal]
black = "0x000000"
blue = "0x0000ff"
cyan = "0x00d0d0"
green = "0x00d000"
magenta = "0xd000d0"
red = "0xd00000"
white = "0xd0d0d0"
yellow = "0xaf8700"

[colors.bright]
black = "0x404040"
blue = "0x3030ff"
cyan = "0x00ffff"
green = "0x00ff00"
magenta = "0xff00ff"
red = "0xff0000"
white = "0xffffff"
yellow = "0xffff00"

[colors.cursor]
cursor = "0xff8000"
text = "0x000000"

[cursor]
blink_interval = 400

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 11.0

[font.normal]
family = "Inconsolata Nerd Font Mono"
style = "Regular"

[font.italic]
family = "Inconsolata Nerd Font Mono"
style = "Italic"

[font.bold]
family = "Inconsolata Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Inconsolata Nerd Font Mono"
style = "Bold Italic"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "CreateNewWindow"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0000"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0000"
key = "Key2"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001"
key = "A"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002"
key = "B"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0004"
key = "D"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0005"
key = "E"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0006"
key = "F"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0007"
key = "G"
mods = "Control"

[[keyboard.bindings]]
chars = "\b"
key = "H"
mods = "Control"

[[keyboard.bindings]]
chars = "\t"
key = "I"
mods = "Control"

[[keyboard.bindings]]
chars = """

"""
key = "J"
mods = "Control"

[[keyboard.bindings]]
chars = "\u000B"
key = "K"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\r"
key = "M"
mods = "Control"

[[keyboard.bindings]]
chars = "\u000E"
key = "N"
mods = "Control"

[[keyboard.bindings]]
chars = "\u000F"
key = "O"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0010"
key = "P"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0012"
key = "R"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0013"
key = "S"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0014"
key = "T"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0015"
key = "U"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0016"
key = "V"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0017"
key = "W"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0018"
key = "X"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0019"
key = "Y"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001A"
key = "Z"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B"
key = "LBracket"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001C"
key = "Backslash"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001D"
key = "RBracket"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
chars = "\u000Ba"
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "G"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B`"
key = "`"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B~"
key = "`"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B!"
key = "Key1"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B@"
key = "Key2"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B#"
key = "Key3"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B$"
key = "Key4"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B%"
key = "Key5"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B^"
key = "Key6"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B&"
key = "Key7"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B*"
key = "Key8"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B("
key = "Key9"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B0"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B)"
key = "Key0"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B-"
key = "Minus"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B_"
key = "Minus"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B="
key = "Equals"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B+"
key = "Equals"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B["
key = "LBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B{"
key = "LBracket"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B]"
key = "RBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B}"
key = "RBracket"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B\\"
key = "Backslash"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B|"
key = "Backslash"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B;"
key = "Semicolon"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B:"
key = "Semicolon"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B:"
key = "Colon"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B'"
key = "'"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\""
key = "'"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B,"
key = "Comma"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B<"
key = "Comma"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B>"
key = "Period"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B/"
key = "Slash"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B?"
key = "Slash"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B "
key = "Space"
mods = "Alt"

[window]
opacity = 0.95
